[acolyt]
author_github = "TxCorpi0x"
author_wallet = ""

[aixbt]
author_github = "bluntbrain"
author_wallet = ""

[allora]
author_github = "TxCorpi0x"
author_wallet = ""

[cdp]
author_github = "hyacinthus"
author_wallet = ""

[common]
author_github = "hyacinthus"
author_wallet = ""

[cryptocompare]
author_github = "0xkieranwilliams"
author_wallet = ""

[cryptopanic]
author_github = "v1ktorrr0x"
author_wallet = ""

[dapplooker]
author_github = "bluntbrain"
author_wallet = ""

[defillama]
author_github = "0xkieranwilliams"
author_wallet = ""

[elfa]
author_github = "TxCorpi0x"
author_wallet = ""

[enso]
author_github = "TxCorpi0x"
author_wallet = ""

[github]
author_github = "bluntbrain"
author_wallet = ""

[goat]
author_github = "TxCorpi0x"
author_wallet = ""

[heurist]
author_github = "hyacinthus"
author_wallet = ""

[moralis]
author_github = "developerfred"
author_wallet = ""

[nation]
author_github = "spidemen"
author_wallet = ""

[openai]
author_github = "hyacinthus"
author_wallet = ""

[slack]
author_github = "hyacinthus"
author_wallet = ""

[tavily]
author_github = "bluntbrain"
author_wallet = ""

[twitter]
author_github = "hyacinthus"
author_wallet = ""

[unrealspeech]
author_github = "bluntbrain"
author_wallet = ""

[unrealspeech]
author_github = "yornfifty"
author_wallet = ""
