name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
        
    - name: Install dependencies
      run: |
        poetry install --with dev
        
    - name: Check formatting with Black
      run: |
        black --check .
        
    - name: Check imports with isort
      run: |
        isort --check-only --diff .
        