name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install poetry
      uses: abatilo/actions-poetry@e78f54a89cb052fff327414dd9ff010b5d2b4dbd
        
    - name: Install dependencies
      run: |
        poetry install --with dev
        
    - name: Ruff Check
      run: |
        poetry run ruff check
