name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install poetry
      uses: abatilo/actions-poetry@v2
        
    - name: Install dependencies
      run: |
        poetry install --with dev
        
    - name: Run Bandit security scan
      run: |
        bandit -r app/ skills/ skill_sets/ utils/ -ll
