name: Build Docker Image and Deploy to TestnetDev

on:
  push:
    branches: [ release/carbon/testnet-dev ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '*.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      -
        name: Get commit message
        id: commit_message
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo -n "${{github.event.head_commit.message}}" | jq -Rsa . | sed -e 's/^"//' -e 's/"$//'
      -
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/GithubActions
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            RELEASE=${{ github.run_number }}
          push: true
          tags: ${{ secrets.AWS_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/intentkit:${{ github.sha }},${{ secrets.AWS_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/intentkit:testnet-dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Deploy to Amazon EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name crestal-production
          kubectl version
          kubectl set image -n testnet-dev deployment/intent-api intent-api=${{ secrets.AWS_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/intentkit:${{ github.sha }}
          kubectl set image -n testnet-dev deployment/intent-autonomous intent-autonomous=${{ secrets.AWS_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/intentkit:${{ github.sha }}
      -
        name: Post to a Slack channel
        if: ${{ success() }}
        id: slack-success
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C0786MHAL8J'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "`${{ github.repository }}`\n*Branch*: `${{ github.ref_name }}`\n*Build result*: (${{ github.run_number }}) *${{ job.status }}* 🟩\n*Changes*:\n${{ steps.commit_message.outputs.value }}\n*Diff*: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      -
        name: Post to a Slack channel
        if: ${{ failure() }}
        id: slack-failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C0786MHAL8J'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "`${{ github.repository }}`\n*Branch*: `${{ github.ref_name }}`\n*Build result*: (${{ github.run_number }}) *${{ job.status }}* 🟥\n*Build Log*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Changes*:\n${{ steps.commit_message.outputs.value }}\n*Diff*: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
